#! /bin/sh



# Start key-event daemon
# TODO: improve this to check whether already running and
# signal reload if so
sxhkd &

# Remove monitors when they are disabled via xrandr (builtin display when docked
bspc config remove_disabled_monitors true

# Standalone (Default config if run without args)
xrandr --output eDP-1 --auto --output DP-2-1 --off --output DP-2-2 --off
bspc monitor -d I II III IV V VI VII VIII IX X

# Docked config for office with two external monitors
#xrandr --output eDP-1 --off --output DP-2-1 --auto --primary --output DP-2-2 --auto --right-of DP-2-1
#bspc monitor DP-2-1 -n 1 -d I II III IV V  
#bspc monitor DP-2-2 -n 2 -d VI VII VIII IX X

# Presentation mode, one external screen with a single desktop
#bspc monitor eDP-1 -d I II III IV V VI VII VIII IX
#bspc monitor HDMI-2 -d X


bspc config border_width         0
bspc config window_gap           0 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus 	 true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Slack desktop='X' follow=off focus=off 
bspc rule -a Skype desktop='X' follow=off focus=off 
bspc rule -a spotify desktop='IX' follow=off focus=off 
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-center ~/Pictures/background/316936_scaled.jpg
